### PR TITLE
Add a diagram for illustration

### LINKED ISSUE #39: Visuals for F# Compiler Technical Overview
Would be nice to have high-level diagram of compiler components for http://fsharp.github.io/2015/09/29/fsharp-compiler-guide.html
or processing pipeline (something like that)

I think that it will be much easier to understand with some visuals.

### PR DESCRIPTION
**Pull request by dungpa**
Close #39.

### CODE REVIEW

**Comment by forki** [comment]
awesome

**Comment by vasily-kirichenko** [comment]
Great.

**Comment by dsyme** [comment]
Great!  The diagram needs a couple of tweaks - have you got the source? e.g. 

* put back-and-forth arrows on the "type checking" line

* have "resolving references"-->"importing DLLs"-->TC be independent from "parsing"-->"TC"

**Comment by dungpa** [comment]
Sure, I'll send another PR.

**Pull request merged**
