### PR TITLE
Update a ton of links to compiler source files

### PR DESCRIPTION
**Pull request by baronfel**
Prepping this document ahead of using it as a reference for my FSSF Mentee.

### CODE REVIEW

**Comment by baronfel** [comment]
@dsyme would you mind taking a look here? It's almost entirely link updates, with very minor rephrasing of one or two descriptions.

**Comment by dsyme** [comment]
Didn't this get moved to dotnet
/fsharp? Shouldn't we use that version and delete this one?

**Comment by baronfel** [comment]
oof, you're exactly right. It's available [here](https://github.com/dotnet/fsharp/blob/main/docs/compiler-guide.md), but I'm not sure what the best way to embed that in this website would be.

**Comment by dsyme** [comment]
>oof, you're exactly right. It's available here, but I'm not sure what the best way to embed that in this website would be.

Suggest deleting all contents here and replacing with a link

**Pull request merged**
